spring:
  profiles:
    active: test

#java -Dspring.profiles.active=local -jar build/libs/jpa-0.0.1-SNAPSHOT.jar

custom:
  property:
    single: custom-property
    comlist: comma, separated, list, to, value
    # PostConstruct로 initialize 진행